import Head from 'next/head'

import { Inter } from '@next/font/google'

import Logo from '@/Components/Logo'
import { useRouter } from 'next/router'







import PokemonCard from '@/Components/PokemonCard'
import NewsPaper from '@/Components/NewsPaper'








export default function Home({ data }) {


  const router = useRouter()




  return (
    <>
      <Head>
        <title>The Ultimate Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;500;700&display=swap" rel="stylesheet">
        </link>

      </Head>
      {/* background shape */}
      <div className='pb-32 px-24' style={{ backgroundImage: `url(/Media-Asset/Background.png)`, backgroundSize: 'cover', backgroundPosition: 'center' }} >
        {/* background texture  */}
        <div className='h-screen  pb-32' style={{ backgroundImage: `url(/Media-Asset/Texture.png)`, backgroundSize: 'cover', backgroundPosition: 'center' }} >
          {/* logo  */}
          <Logo></Logo>

          {/* contents  */}
          <div className='grid grid-cols-1 md:grid-cols-3 lg:grid-cols-5 gap-y-10 gap-x-20 pt-10'>
            {
              data?.data?.pokemons?.results?.map((poke, idx) => <PokemonCard key={idx} poke={poke} idx={idx} ></PokemonCard>)
            }
          </div>
        </div>
      </div>

      {/* newspaper  */}
      <div>
        <NewsPaper></NewsPaper>
      </div>

    </>
  )
}



export async function getStaticProps() {
  const gqlQuery = `query pokemons($limit: Int, $offset: Int) {
    pokemons(limit: $limit, offset: $offset) {
      count
      next
      previous
      status
      message
      results {
        url
        name
        image
      }
    }
  }`;

  const gqlVariables = {
    limit: 10,
    offset: 0,
  };

  const res = await fetch('https://graphql-pokeapi.graphcdn.app/', {
    credentials: 'omit',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      query: gqlQuery,
      variables: gqlVariables,
    }),
    method: 'POST',
  });

  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}


