import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Logo from '@/Components/Logo'
import { useRouter } from 'next/router'


import { ApolloProvider } from '@apollo/client';
import ApolloClient from '@apollo/client';

import { AppProps } from 'next/app'
import PokemonCard from '@/Components/PokemonCard'
// import bgImageDesign from './Media-Asset/Background.png'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  // console.log(data.data.pokemons?.results);

  const router = useRouter()



  return (
    <>
      <Head>
        <title>The Ultimate Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* background shape */}
      <div className='pb-32' style={{ backgroundImage: `url(/Media-Asset/Background.png)`, backgroundSize: 'cover', backgroundPosition: 'center' }} >
        {/* background texture  */}
        <div className='h-screen px-24' style={{ backgroundImage: `url(/Media-Asset/Texture.png)`, backgroundSize: 'cover', backgroundPosition: 'center' }} >
          {/* logo  */}
          <Logo></Logo>

          {/* contents  */}
          <div className='grid grid-cols-1 md:grid-cols-3 lg:grid-cols-5 gap-y-10 gap-x-20 pt-10'>
            {
              data?.data?.pokemons?.results?.map((poke,idx) => <PokemonCard key={idx} poke={poke} ></PokemonCard>)
            }
          </div>
        </div>
      </div>
    </>
  )
}



export async function getStaticProps() {
  const gqlQuery = `query pokemons($limit: Int, $offset: Int) {
    pokemons(limit: $limit, offset: $offset) {
      count
      next
      previous
      status
      message
      results {
        url
        name
        image
      }
    }
  }`;

  const gqlVariables = {
    limit: 10,
    offset: 0,
  };

  const res = await fetch('https://graphql-pokeapi.graphcdn.app/', {
    credentials: 'omit',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      query: gqlQuery,
      variables: gqlVariables,
    }),
    method: 'POST',
  });

  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}
